### ISSUE TITLE
missing permission issues; Solved

### ISSUE THREAD

**Issue by Creeper55k** [Creeper55k/ANormalBot#1]
at item.request.gen.end (/rbd/pnpm-volume/71b5ddd8-2a78-46fc-aba4-68049f14880d/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/rbd/pnpm-volume/71b5ddd8-2a78-46fc-aba4-68049f14880d/node_modules/.registry.npmjs.org/snekfetch/3.6.4/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'DiscordAPIError',
  message: 'Missing Permissions',
  path: '/api/v7/channels/265156361791209475/messages',
  code: 50013,
  method: 'POST' } Promise {

Solution: missing package; snekfetch

**Comment by Creeper55k** [comment]
nvm, not solved

**Comment by Creeper55k** [comment]
Answer: unsolvable but won't affect anything: server mute
